set nocompatible
syntax on
filetype plugin indent on

set number
set relativenumber
set cursorline
set showmatch
set laststatus=2
set scrolloff=5

set tabstop=4
set shiftwidth=4
set expandtab
set autoindent

set hlsearch
set incsearch
set ignorecase
set smartcase

set encoding=utf-8
set backspace=indent,eol,start
set mouse=a
set noswapfile
